name: 'PR GIF Bot'
description: 'Posts themed GIFs on PR events'
author: 'matthewdavidson09'
inputs:
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
