name: 'PR GIF Bot'
description: 'Posts themed GIFs on pull request events'
author: 'Matthew Davidson'

inputs:
  github_token:
    description: 'GitHub token for posting comments'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/matthewdavidson09/gifbot:latest'
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}

branding:
  color: 'purple'
  icon: 'zap'
