name: Test GIF Bot Locally

on:
  pull_request:
    types: [opened, closed, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run local action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
