name: Test GIF Bot Locally

on:
  pull_request:
    types: [opened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run action from local Dockerfile
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
